version: '2'
services:
  namesrv:
    image: rocketmqinc/rocketmq
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./data/logs:/root/logs
      - ./data/store:/root/store
    environment:
      - JAVA_OPT_EXT=-server -Xms128m -Xmx128m -Xmn128m
    command: sh mqnamesrv
  broker:
    image: rocketmqinc/rocketmq
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ./data/logs:/root/logs
      - ./data/store:/root/store
      - /usr/local/mq/rocketmq/broker.conf:/opt/rocketmq/conf/broker.conf
    #command: sh mqbroker -n namesrv:9876
    command: sh mqbroker -n namesrv:9876 -c ../conf/broker.conf
    depends_on:
      - namesrv
    environment:
      - JAVA_HOME=/usr/lib/jvm/jre
      - JAVA_OPT_EXT=-server -Xms128m -Xmx128m -Xmn128m
  console:
    image: styletang/rocketmq-console-ng
    container_name: rocketmq-console-ng
    ports:
      - 8080:8080
    depends_on:
      - namesrv
    environment:
      - JAVA_OPTS= -Dlogging.level.root=info   -Drocketmq.namesrv.addr=rmqnamesrv:9876 
      - JAVA_OPT_EXT=-server -Xms128m -Xmx128m -Xmn128m
      - Dcom.rocketmq.sendMessageWithVIPChannel=false

